name = "rag-example"
main = "src/index.js"
compatibility_date = "2024-03-29"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "rag-example"
database_id = "cc04870d-2a74-4d5e-a8bf-9dcb18658e35"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "rag-example-webinar-index"

[ai]
binding = "AI"
